service: json-collect
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  profile: yolandi-admin
  region: eu-west-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  json-collect:
    handler: bin/json-collect
    events:
      - http:
          path: json-collect
          method: post

